import { TemplateDefinition } from '@/types';

export const TEMPLATES_DATA: TemplateDefinition[] = [
  // 1. MINIMAL NUDE (Elegante & Sobria)
  {
    id: 'minimal-nude',
    name: '1. Minimal Nude (Elegante & Sobria)',
    category: 'boda',
    badge: 'Sobriedad & Distinción',
    // Papelería fina de boda en tonos beige, lino, crema y tipografía serif elegante
    thumbnail: 'https://images.unsplash.com/photo-1607190074257-dd4b7af0309f?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1607190074257-dd4b7af0309f?auto=format&fit=crop&w=1200&q=80',
    description: 'Estética escandinava en tonos arena y beige con tipografía serif ultra delgada. Transiciones suaves fade-in & slide-up progresivas para máxima sobriedad y pureza visual.',
    tags: ['Minimalista', 'Arena & Beige', 'Serif Delgada', 'Editorial Escandinavo', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'minimal-nude',
      templateName: 'Minimal Nude',
      primaryColor: '#7A6E60', // Arena/Marrón sobrio
      secondaryColor: '#FAF8F5', // Crema suave
      backgroundColor: '#F5F2EB', // Nude / Beige escandinavo
      textColor: '#3A332C', // Carbón cálido suave
      accentColor: '#A89F91', // Acento arena sutil
      cardBackground: 'rgba(255, 255, 255, 0.75)',
      fontFamilyTitle: 'Cormorant Garamond',
      fontFamilyBody: 'Montserrat',
      // Foto editorial de novios sobria y cinematográfica
      coverImageUrl: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 6,
      galleryImages: [
        'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=800&q=80', // Pareja editorial
        'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80', // Anillos & Joyería minimal
        'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80', // Vestido & Texturas
        'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', // Mesa & Decoración sobria
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80', // Detalle floral seco
        'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80', // Arquitectura de boda
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'fade',
        animationIntensity: 'low',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'acustico',
        trackName: 'Pista 3: Acústico Suave & Ambient',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'ELENA & MATEO',
          subtitle: 'TE INVITAMOS A CELEBRAR JUNTOS',
          dateText: 'SÁBADO 18 DE OCTUBRE, 2026',
          timeText: '17:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-10-18T17:00:00',
        },
        story: {
          enabled: true,
          title: 'Nuestra Historia',
          content: 'Un amor que creció con la calma del tiempo y la certeza del alma. Queremos compartir este nuevo capítulo en un espacio de paz, armonía y absoluta elegancia.',
          image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Itinerario del Gran Día',
          items: [
            { time: '17:00 HRS', title: 'Ceremonia de Votos', description: 'Jardín de los Olivos' },
            { time: '18:30 HRS', title: 'Brindis & Cóctel de Bienvenida', description: 'Terraza Principal' },
            { time: '20:00 HRS', title: 'Cena Íntima de Gala', description: 'Comedor Central' },
            { time: '22:00 HRS', title: 'Celebración & Música', description: 'Pista Principal' },
          ],
        },
        location: {
          enabled: true,
          title: 'Ubicación del Evento',
          venueName: 'Casa Albaricoque',
          address: 'Camino del Valle #102, Valle de Bravo',
          city: 'Estado de México, México',
          googleMapsUrl: 'https://maps.google.com/?q=Valle+de+Bravo+Mexico',
          wazeUrl: 'https://waze.com/ul?q=Valle+de+Bravo+Mexico',
        },
        gallery: {
          enabled: true,
          title: 'Galería de Recuerdos',
          images: [
            'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
          ],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Elegancia Neutra / Tonos Nude & Arena',
          description: 'Sugerimos paleta de colores beige, arena, olivo suave y tonos tierra cálidos.',
          colors: ['#7A6E60', '#A89F91', '#F5F2EB', '#FAF8F5'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'Tu compañía y buenos deseos son nuestro mejor obsequio.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Confirmación de Asistencia (RSVP)',
          deadline: '2026-09-15',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Agradecemos confirmar tu asistencia antes del 15 de Septiembre para garantizar tu lugar.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase Digital Minimal',
          instructions: 'Muestra este boleto al ingresar.',
        },
      },
    },
  },

  // 2. BOTANICAL GARDEN (Boho / Orgánica)
  {
    id: 'botanical-garden',
    name: '2. Botanical Garden (Boho / Orgánica)',
    category: 'boda',
    badge: 'Sobre Botánico & Follaje',
    // Papelería botánica fina de boda con sobre artesanal, sello de lacre y ramas de eucalipto sobre lino
    thumbnail: 'https://images.unsplash.com/photo-1509927083803-4bd519298ac4?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1509927083803-4bd519298ac4?auto=format&fit=crop&w=1200&q=80',
    description: 'Apertura con sobre digital botánico y música instrumental. Fondo texturizado con follaje acuarelado, dos sedes (iglesia y recepción), calendario interactivo y galería lightbox.',
    tags: ['Sobre Botánico', 'Verde Salvia & Crema', 'Música de Entrada', 'Dos Sedes', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'botanical-garden',
      templateName: 'Botanical Garden',
      primaryColor: '#8A9A86', // Verde salvia
      secondaryColor: '#FDFBF7', // Crema suave
      backgroundColor: '#FDFBF7', // Base crema texturizada
      textColor: '#2D4A3E', // Verde bosque profundo
      accentColor: '#4A5D4E', // Verde oliva / ficus
      cardBackground: 'rgba(253, 251, 247, 0.88)',
      fontFamilyTitle: 'Playfair Display',
      fontFamilyBody: 'Montserrat',
      // Foto romántica en jardín
      coverImageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 6,
      galleryImages: [
        'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', // Pareja en jardín
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80', // Arreglo floral y velas
        'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80', // Ramo silvestre
        'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80', // Mesa en el bosque
        'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80', // Anillos sobre madera
        'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80', // Detalle botánico
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'petals',
        animationIntensity: 'medium',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'romantico',
        trackName: 'Pista 1: Instrumental Romántico',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'VALERIA & SEBASTIÁN',
          subtitle: 'TE INVITAMOS A CELEBRAR NUESTRA UNIÓN',
          dateText: 'SÁBADO 14 DE NOVIEMBRE, 2026',
          timeText: '16:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-11-14T16:00:00',
        },
        story: {
          enabled: true,
          title: 'Nuestra Conexión Natural',
          content: 'El amor es la flor que florece en todas las estaciones. Nos llena de profunda alegría dar el sí rodeados de la paz de los árboles y la compañía de quienes más amamos.',
          image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Itinerario en el Jardín',
          items: [
            { time: '16:00 HRS', title: 'Ceremonia al Aire Libre', description: 'Bajo el Gran Olivo Ancestral' },
            { time: '17:30 HRS', title: 'Cóctel & Música Acústica', description: 'Jardín de las Fuentes Botánicas' },
            { time: '19:00 HRS', title: 'Cena Bajo las Luces', description: 'Terraza de Enredaderas' },
            { time: '21:30 HRS', title: 'Fiesta, Brindis & Baile', description: 'Pista Iluminada' },
          ],
        },
        location: {
          enabled: true,
          title: 'El Santuario Botánico',
          venueName: 'Hacienda de los Eucaliptos',
          address: 'Carretera San Miguel - Dolores Km 8',
          city: 'San Miguel de Allende, Gto.',
          googleMapsUrl: 'https://maps.google.com/?q=San+Miguel+de+Allende+Guanajuato',
          wazeUrl: 'https://waze.com/ul?q=San+Miguel+de+Allende+Guanajuato',
        },
        gallery: {
          enabled: true,
          title: 'Galería de Recuerdos Botánicos',
          images: [
            'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
          ],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Boho Chic / Guayabera & Vestido Botánico',
          description: 'Hombres: Guayabera de lino clara o traje en tonos arena/verde. Mujeres: Vestido midi o largo en tonos florales o salvia.',
          colors: ['#8A9A86', '#4A5D4E', '#D3B48C', '#FDFBF7'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'El mejor regalo es tu compañía en nuestro gran día.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Confirmación de Asistencia (RSVP)',
          deadline: '2026-10-01',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Agradecemos confirmar tu asistencia antes del 1 de Octubre para organizar tu asiento en el jardín.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase Digital Botánico',
          instructions: 'Presenta tu código al llegar al jardín.',
        },
      },
    },
  },

  // 3. TECH-LUXURY (Moderna / Exclusiva)
  {
    id: 'tech-luxury',
    name: '3. Tech-Luxury (Moderna / Exclusiva)',
    category: 'boda',
    badge: 'Glassmorphism & Bokeh Oro',
    thumbnail: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
    description: 'Fondo oscuro azul medianoche/negro obsidiana con tarjetas de vidrio pulido (glassmorphism), bordes biselados en oro y partículas bokeh flotantes.',
    tags: ['Glassmorphism', 'Fondo Oscuro', 'Bokeh Oro', 'Galería Carrusel', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'tech-luxury',
      templateName: 'Tech-Luxury',
      primaryColor: '#D3B48C',
      secondaryColor: '#162E2D',
      backgroundColor: '#0A0A0C',
      textColor: '#FAF6F0',
      accentColor: '#EADBC6',
      cardBackground: 'rgba(255, 255, 255, 0.05)',
      fontFamilyTitle: 'Cinzel',
      fontFamilyBody: 'Montserrat',
      coverImageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 6,
      galleryImages: [
        'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'bokeh',
        animationIntensity: 'high',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'brisa',
        trackName: 'Pista 5: Brisa & Piano Relax',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'SANTIAGO & CAMILA',
          subtitle: 'THE LUXURY WEDDING EXPERIENCE',
          dateText: 'SÁBADO 28 DE NOVIEMBRE, 2026',
          timeText: '19:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-11-28T19:00:00',
        },
        story: {
          enabled: true,
          title: 'Exclusividad & Visión',
          content: 'Una velada contemporánea donde la tecnología y la alta costura se encuentran para celebrar nuestra historia de amor.',
          image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Timeline VIP',
          items: [
            { time: '19:00 HRS', title: 'Black Tie Reception', description: 'Glass Pavilion' },
            { time: '20:30 HRS', title: 'Signature Dinner & Toast', description: 'Imperial Room' },
            { time: '22:30 HRS', title: 'After Party & Sound Experience', description: 'The Lounge' },
          ],
        },
        location: {
          enabled: true,
          title: 'The Venue',
          venueName: 'The St. Regis Sky Ballroom',
          address: 'Paseo de la Reforma 439',
          city: 'Ciudad de México, CDMX',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Visual Gallery',
          images: [
            'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
          ],
        },
        dressCode: {
          enabled: true,
          title: 'Dress Code',
          type: 'Black Tie / Gala Vanguardista',
          description: 'Hombres: Smoking negro clásico. Mujeres: Vestido de gala largo en negro, dorado o plata.',
          colors: ['#0A0A0C', '#D3B48C', '#EADBC6', '#FAF6F0'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'Agradecemos tu compañía en esta noche única.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'RSVP Confirmation',
          deadline: '2026-10-20',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Acceso estrictamente con confirmación digital previa.',
        },
        qrPass: {
          enabled: true,
          title: 'VIP Pass QR',
          instructions: 'Escanea tu pase en la recepción del Sky Ballroom.',
        },
      },
    },
  },

  // 4. ROYAL GOLD (Clásica / Boda de Gran Gala)
  {
    id: 'royal-gold',
    name: '4. Royal Gold (Clásica / Gran Gala)',
    category: 'boda',
    badge: 'Sobre de Lacre & Anillos',
    thumbnail: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
    description: 'Marcos ornamentales barrocos en marfil y oro imperial. Animación exclusiva de apertura de sobre con sello de lacre rojo y anillos dorados flotantes.',
    tags: ['Sobre de Lacre', 'Marfil & Oro', 'Gran Gala', '1 Foto Enmarcada', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'royal-gold',
      templateName: 'Royal Gold',
      primaryColor: '#B89758',
      secondaryColor: '#FAF6F0',
      backgroundColor: '#FAF6F0',
      textColor: '#1A1814',
      accentColor: '#D3B48C',
      cardBackground: 'rgba(255, 255, 255, 0.96)',
      fontFamilyTitle: 'Playfair Display',
      fontFamilyBody: 'Lato',
      coverImageUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 1,
      galleryImages: [
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'envelope',
        animationIntensity: 'high',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: true,
      },
      audio: {
        trackId: 'romantico',
        trackName: 'Pista 1: Instrumental Romántico',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'ANA & CARLOS',
          subtitle: 'TIENEN EL HONOR DE INVITARLE A SU MATRIMONIO',
          dateText: 'SÁBADO • XIV • NOVIEMBRE • MMXXVI',
          timeText: '18:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-11-14T18:00:00',
        },
        story: {
          enabled: true,
          title: 'Nuestra Unión Solemne',
          content: 'Con la bendición de Dios y de nuestras familias, consagramos nuestras vidas en santa unión matrimonial.',
          image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Orden de la Celebración',
          items: [
            { time: '18:00 HRS', title: 'Solemne Ceremonia Religiosa', description: 'Capilla Mayor' },
            { time: '19:30 HRS', title: 'Brindis & Recepción de Gala', description: 'Jardín de los Arcos' },
            { time: '21:00 HRS', title: 'Banquete Real & Baile', description: 'Gran Salón Virreinal' },
          ],
        },
        location: {
          enabled: true,
          title: 'Sede Nupcial',
          venueName: 'Hacienda San José de Gracia',
          address: 'Camino Virreinal Km 12',
          city: 'Puebla, Pue.',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Retrato Real',
          images: ['https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80'],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Rigurosa Etiqueta / Gala',
          description: 'Caballeros: Esmoquin o Frac oscuro. Damas: Vestido largo de gala.',
          colors: ['#8A1C14', '#B89758', '#FAF6F0'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'El mayor regalo es compartir este día con ustedes.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'S.R.C. • Confirmación',
          deadline: '2026-10-14',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Se ruega contestación antes del 14 de Octubre.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase de Gala QR',
          instructions: 'Presente su pase de gala en recepción.',
        },
      },
    },
  },

  // 5. GLOW PARTY (XV Años / Fiesta Juvenil)
  {
    id: 'glow-party',
    name: '5. Glow Party (XV Años / Fiesta Juvenil)',
    category: 'xv',
    badge: 'Luces Neón & Destellos',
    thumbnail: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    description: 'Paleta vibrante neón y pastel magenta/cian con tipografía urbana. Luces de fiesta en movimiento suave y destellos interactivos al presionar botones.',
    tags: ['XV Años', 'Luces Neón', 'Moderna & Urbana', 'Galería Dinámica', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'glow-party',
      templateName: 'Glow Party',
      primaryColor: '#E0218A',
      secondaryColor: '#120826',
      backgroundColor: '#0D051A',
      textColor: '#FFFFFF',
      accentColor: '#00F0FF',
      cardBackground: 'rgba(28, 12, 54, 0.85)',
      fontFamilyTitle: 'Montserrat',
      fontFamilyBody: 'Inter',
      coverImageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 8,
      galleryImages: [
        'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'glow-lights',
        animationIntensity: 'high',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'fiesta',
        trackName: 'Pista 4: Fiesta & Pop Instrumental',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'REGINA • MIS XV AÑOS',
          subtitle: 'THE GLOW NIGHT CELEBRATION',
          dateText: 'SÁBADO 05 DE DICIEMBRE, 2026',
          timeText: '20:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-12-05T20:00:00',
        },
        story: {
          enabled: true,
          title: 'Una Noche Inolvidable',
          content: 'Llegó el momento de celebrar mis 15 años en una fiesta llena de música, luces y grandes momentos con mis personas favoritas.',
          image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Fiesta & Show',
          items: [
            { time: '20:00 HRS', title: 'Red Carpet & Bienvenida Neon', description: 'Lobby Principal' },
            { time: '21:30 HRS', title: 'Vals Soñado & Brindis', description: 'Pista de Luces' },
            { time: '22:30 HRS', title: 'DJ Live Set & Glow Party', description: 'Club Room' },
          ],
        },
        location: {
          enabled: true,
          title: 'Lugar de la Fiesta',
          venueName: 'Salón Crystal Lights',
          address: 'Av. Las Palmas #450',
          city: 'Monterrey, N.L.',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Sesión XV',
          images: [
            'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
          ],
        },
        dressCode: {
          enabled: true,
          title: 'Dress Code',
          type: 'Glow Chic / Vestido & Traje Moderno',
          description: '¡Ven listo para brillar! Acentos metálicos o neón bienvenidos.',
          colors: ['#E0218A', '#00F0FF', '#9900FF', '#FFFFFF'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'Si deseas obsequiarme un detalle:',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: '¡Confirma tu Pase a la Fiesta!',
          deadline: '2026-11-15',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Confirma tu asistencia antes del 15 de Noviembre.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase Digital Neon',
          instructions: 'Muestra tu código para ingresar a la fiesta.',
        },
      },
    },
  },

  // 6. CINEMATIC NIGHT (Graduaciones / Galas)
  {
    id: 'cinematic-night',
    name: '6. Cinematic Night (Graduaciones / Galas)',
    category: 'graduacion',
    badge: 'Confeti 3D & Birretes',
    thumbnail: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
    description: 'Fondo azul medianoche profundo con contrastes en blanco brillante y plata metálica. Caída sutil de birretes vectoriales y confeti tridimensional.',
    tags: ['Graduación', 'Azul Medianoche', 'Plata & Confeti', 'Galería Cuadrícula', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'cinematic-night',
      templateName: 'Cinematic Night',
      primaryColor: '#3B82F6',
      secondaryColor: '#0F172A',
      backgroundColor: '#030712',
      textColor: '#F8FAFC',
      accentColor: '#94A3B8',
      cardBackground: 'rgba(15, 23, 42, 0.85)',
      fontFamilyTitle: 'Cinzel',
      fontFamilyBody: 'Inter',
      coverImageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 6,
      galleryImages: [
        'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'confetti-caps',
        animationIntensity: 'medium',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'vals',
        trackName: 'Pista 2: Vals Elegante & Clásico',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'GENERACIÓN DE EXCELENCIA 2026',
          subtitle: 'GALA DE GRADUACIÓN • NOCHE DE HONOR',
          dateText: 'VIERNES 10 DE JULIO, 2026',
          timeText: '19:30 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-07-10T19:30:00',
        },
        story: {
          enabled: true,
          title: 'El Fin de una Gran Etapa',
          content: 'Años de esfuerzo, compañerismo y dedicación culminan en esta noche estelar de celebración y éxito.',
          image: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Protocolo de la Gala',
          items: [
            { time: '19:30 HRS', title: 'Recepción & Alfombra Azul', description: 'Foyer Principal' },
            { time: '20:30 HRS', title: 'Entrega de Reconocimientos', description: 'Auditorio Magna' },
            { time: '21:30 HRS', title: 'Cena de Gala & Brindis de Honor', description: 'Gran Salón' },
          ],
        },
        location: {
          enabled: true,
          title: 'Sede de la Gala',
          venueName: 'Centro Internacional de Convenciones',
          address: 'Av. Fundadores #100',
          city: 'Guadalajara, Jal.',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Momentos de Graduación',
          images: ['https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=800&q=80'],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Riguroso Traje de Noche / Smoking',
          description: 'Caballeros: Traje formal oscuro. Damas: Vestido largo de gala.',
          colors: ['#030712', '#3B82F6', '#94A3B8', '#F8FAFC'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Honor',
          description: 'Agradecemos compartir este triunfo juntos.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Confirmación de Asistencia',
          deadline: '2026-06-25',
          maxCompanionsPerGuest: 4,
          allowDietaryRestrictions: true,
          customMessage: 'Confirma tus boletos antes del 25 de Junio.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase QR de Graduación',
          instructions: 'Presenta este boleto en la puerta de acceso.',
        },
      },
    },
  },

  // 7. SWEET CELEBRATION (Infantil / Bautizo / Baby Shower)
  {
    id: 'sweet-celebration',
    name: '7. Sweet Celebration (Infantil / Bautizo)',
    category: 'bautizo',
    badge: 'Nubes Flotantes & Estrellas',
    thumbnail: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
    description: 'Tonos pastel suaves (rosa tierno, azul cielo y amarillo manteca) con ilustraciones delicadas. Nubes flotando suavemente y estrellas titilantes.',
    tags: ['Bautizo', 'Baby Shower', 'Tonos Pastel', '1 Foto Suavizada', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'sweet-celebration',
      templateName: 'Sweet Celebration',
      primaryColor: '#7AA7C7',
      secondaryColor: '#FFFDF9',
      backgroundColor: '#EAF4FC',
      textColor: '#2C3E50',
      accentColor: '#F5C6CB',
      cardBackground: 'rgba(255, 255, 255, 0.95)',
      fontFamilyTitle: 'Playfair Display',
      fontFamilyBody: 'Lato',
      coverImageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 1,
      galleryImages: [
        'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'clouds-stars',
        animationIntensity: 'medium',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'acustico',
        trackName: 'Pista 3: Acústico Suave & Ambient',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'EL BAUTIZO DE MATÍAS',
          subtitle: 'MI PRIMER SACRAMENTO',
          dateText: 'SÁBADO 10 DE OCTUBRE, 2026',
          timeText: '12:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-10-10T12:00:00',
        },
        story: {
          enabled: true,
          title: 'Bendición Angelical',
          content: '«Que los ángeles te cuiden y la luz de Dios guíe cada uno de tus pasos». Los invitamos a celebrar el bautizo de nuestro pequeño.',
          image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Misa & Celebración',
          items: [
            { time: '12:00 HRS', title: 'Santa Misa de Bautizo', description: 'Templo Expiatorio' },
            { time: '14:00 HRS', title: 'Comida & Brindis Familiar', description: 'Jardín Las Nubes' },
          ],
        },
        location: {
          enabled: true,
          title: 'Lugar de la Recepción',
          venueName: 'Jardín Las Nubes',
          address: 'Calle del Paraíso #88',
          city: 'Querétaro, Qro.',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Retrato de Matías',
          images: ['https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80'],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Formal Claro / Tonos Pastel',
          description: 'Recomendamos tonos claros, blanco, celeste o rosa suave.',
          colors: ['#7AA7C7', '#F5C6CB', '#EAF4FC', '#FFFFFF'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'Agradecemos tu cariño y compañía.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Confirmación Familiar',
          deadline: '2026-09-20',
          maxCompanionsPerGuest: 3,
          allowDietaryRestrictions: true,
          customMessage: 'Por favor confirma antes del 20 de Septiembre.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase de Entrada',
          instructions: 'Muestra este boleto al ingresar.',
        },
      },
    },
  },

  // 8. ROMANCE CLÁSICO (Inspiración Romeo & Julieta)
  {
    id: 'romance-clasico',
    name: '8. Romance Clásico (Romeo & Julieta)',
    category: 'boda',
    badge: 'Palomas & Floración Guinda',
    thumbnail: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80',
    description: 'Textura artesanal tipo pergamino, caligrafía manuscrita y acentos en rojo guinda/vino. Vuelo sutil de dos palomas y floración en las esquinas.',
    tags: ['Romance', 'Pergamino & Vino', 'Vuelo de Palomas', '1 Foto Vintage', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'romance-clasico',
      templateName: 'Romance Clásico',
      primaryColor: '#722F37',
      secondaryColor: '#FAF3E0',
      backgroundColor: '#F7EFE2',
      textColor: '#2A1810',
      accentColor: '#C49A45',
      cardBackground: 'rgba(253, 248, 237, 0.94)',
      fontFamilyTitle: 'Playfair Display',
      fontFamilyBody: 'Lato',
      coverImageUrl: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 1,
      galleryImages: [
        'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'doves-floral',
        animationIntensity: 'medium',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'romantico',
        trackName: 'Pista 1: Instrumental Romántico',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'JULIETA & ROMEO',
          subtitle: 'NUESTRO AMOR ETERNO',
          dateText: 'SÁBADO 24 DE OCTUBRE, 2026',
          timeText: '17:30 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-10-24T17:30:00',
        },
        story: {
          enabled: true,
          title: 'El Encuentro de Dos Almas',
          content: '«Dos estrellas que se encontraron en el firmamento para no separarse jamás». Celebramos la promesa de amarnos por siempre.',
          image: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Itinerario de Gala',
          items: [
            { time: '17:30 HRS', title: 'Ceremonia en el Claustro', description: 'Capilla del Amor Eterno' },
            { time: '19:00 HRS', title: 'Brindis & Música Barroca', description: 'Patio de los Jazmines' },
            { time: '20:30 HRS', title: 'Banquete Romántico', description: 'Gran Salón Renacentista' },
          ],
        },
        location: {
          enabled: true,
          title: 'El Claustro Romántico',
          venueName: 'Castillo San Jerónimo',
          address: 'Antigua Calzada Real #15',
          city: 'Zacatecas, Zac.',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Retrato Vintage',
          images: ['https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=800&q=80'],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Rigurosa Etiqueta / Tonos Vino & Borgoña',
          description: 'Hombres: Traje oscuro. Mujeres: Vestido largo en tonos vino, guinda o dorado.',
          colors: ['#722F37', '#C49A45', '#F7EFE2', '#2A1810'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'Tu presencia es el regalo más preciado.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Confirmación RSVP',
          deadline: '2026-09-30',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Agradecemos confirmar tu asistencia antes del 30 de Septiembre.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase Clásico QR',
          instructions: 'Presenta este boleto en la entrada del castillo.',
        },
      },
    },
  },

  // 9. ELEGANCIA EJECUTIVA (Eventos Empresariales / Aniversarios)
  {
    id: 'elegancia-ejecutiva',
    name: '9. Elegancia Ejecutiva (Empresarial)',
    category: 'empresarial',
    badge: 'Geometría Abstracta & Bronce',
    thumbnail: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    description: 'Diseño corporativo de alto nivel en gris carbón y bronce cepillado con tarjetas estructuradas y líneas geométricas abstractas en movimiento lento.',
    tags: ['Corporativo', 'Gris Carbón & Bronce', 'Geometría Lenta', '1 Foto / Logo', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'elegancia-ejecutiva',
      templateName: 'Elegancia Ejecutiva',
      primaryColor: '#475569',
      secondaryColor: '#F8FAFC',
      backgroundColor: '#E2E8F0',
      textColor: '#0F172A',
      accentColor: '#B45309',
      cardBackground: 'rgba(255, 255, 255, 0.95)',
      fontFamilyTitle: 'Cinzel',
      fontFamilyBody: 'Inter',
      coverImageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 1,
      galleryImages: [
        'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'geometry',
        animationIntensity: 'low',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'brisa',
        trackName: 'Pista 5: Brisa & Piano Relax',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'CUMBRE EJECUTIVA & GALA 2026',
          subtitle: 'ANIVERSARIO CORPORATIVO • LEADERSHIP SUMMIT',
          dateText: 'JUEVES 17 DE SEPTIEMBRE, 2026',
          timeText: '18:30 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-09-17T18:30:00',
        },
        story: {
          enabled: true,
          title: 'Celebrando el Liderazgo',
          content: '25 años transformando industrias y creando valor. Nos complace invitar a nuestros socios y directivos a una velada de distinción y networking de alto impacto.',
          image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Programa Ejecutivo',
          items: [
            { time: '18:30 HRS', title: 'Executive Welcome & Cocktail', description: 'Atrium Terrace' },
            { time: '19:45 HRS', title: 'Keynote & Aniversario Speech', description: 'Main Auditorium' },
            { time: '21:00 HRS', title: 'Cena de Gala & Networking VIP', description: 'Executive Lounge' },
          ],
        },
        location: {
          enabled: true,
          title: 'Sede Corporativa',
          venueName: 'Torre Mayor Executive Club',
          address: 'Av. Paseo de la Reforma 505, Piso 51',
          city: 'Ciudad de México, CDMX',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Logotipo & Emblema',
          images: ['https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80'],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Business Formal / Traje Ejecutivo',
          description: 'Traje de negocios oscuro o vestido sastre ejecutivo.',
          colors: ['#0F172A', '#475569', '#B45309', '#E2E8F0'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Confirmación Institucional',
          description: 'Evento privado con registro restringido por credencial.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Registro de Asistencia VIP',
          deadline: '2026-09-01',
          maxCompanionsPerGuest: 1,
          allowDietaryRestrictions: true,
          customMessage: 'Confirme su asistencia para coordinar su pase de seguridad.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase Ejecutivo QR',
          instructions: 'Presente este código en los torniquetes de acceso.',
        },
      },
    },
  },

  // 10. TROPICAL SUNSET (Bodas / Playa / Jardín)
  {
    id: 'tropical-sunset',
    name: '10. Tropical Sunset (Playa & Jardín)',
    category: 'boda',
    badge: 'Brisa de Palmeras & Sol',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    previewImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: 'Cálidos tonos atardecer, terracota y mostaza con integración panorámica. Sutil movimiento de brisa en palmeras/hojas tropicales y destellos dorados.',
    tags: ['Playa & Jardín', 'Terracota & Ocaso', 'Brisa Tropical', 'Galería Panorámica', 'Boda de Lujo'],
    isPremium: true,
    defaultDesign: {
      templateId: 'tropical-sunset',
      templateName: 'Tropical Sunset',
      primaryColor: '#C85A32',
      secondaryColor: '#FFF8F0',
      backgroundColor: '#FDEEE2',
      textColor: '#2D1B12',
      accentColor: '#E6953B',
      cardBackground: 'rgba(255, 255, 255, 0.94)',
      fontFamilyTitle: 'Playfair Display',
      fontFamilyBody: 'Montserrat',
      coverImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      galleryCapacity: 8,
      galleryImages: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
      ],
      effects: {
        backgroundAnimation: true,
        animationType: 'tropical-breeze',
        animationIntensity: 'high',
        soundEnabled: true,
        microInteractions: true,
        hasEnvelopeIntro: false,
      },
      audio: {
        trackId: 'brisa',
        trackName: 'Pista 5: Brisa & Piano Relax',
        musicAutoplay: false,
      },
      sections: {
        hero: {
          enabled: true,
          title: 'LUCÍA & ALEJANDRO',
          subtitle: 'NUESTRA BODA FRENTE AL MAR',
          dateText: 'SÁBADO 07 DE NOVIEMBRE, 2026',
          timeText: '17:00 HRS',
          backgroundImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        },
        countdown: {
          enabled: true,
          targetDate: '2026-11-07T17:00:00',
        },
        story: {
          enabled: true,
          title: 'Nuestro Atardecer Inolvidable',
          content: 'Con el mar como testigo y el sonido de las olas como música de fondo, prometemos amarnos y caminar juntos en este nuevo viaje.',
          image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        },
        schedule: {
          enabled: true,
          title: 'Itinerario Playero',
          items: [
            { time: '17:00 HRS', title: 'Ceremonia al Atardecer', description: 'Playa Punta Esmeralda' },
            { time: '18:30 HRS', title: 'Cóctel Tropical & Música Chill', description: 'Deck de la Playa' },
            { time: '20:00 HRS', title: 'Cena Bajo las Palmeras', description: 'Terraza Ocaso' },
            { time: '22:00 HRS', title: 'Fiesta & Fogata Frente al Mar', description: 'Pista Arena' },
          ],
        },
        location: {
          enabled: true,
          title: 'Sede en la Playa',
          venueName: 'Hotel Boutique Punta Palmilla',
          address: 'Km 27.5 Carretera Costera',
          city: 'Los Cabos, B.C.S.',
          googleMapsUrl: 'https://maps.google.com',
          wazeUrl: 'https://waze.com',
        },
        gallery: {
          enabled: true,
          title: 'Galería Panorámica',
          images: [
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
          ],
        },
        dressCode: {
          enabled: true,
          title: 'Código de Vestimenta',
          type: 'Guayabera Formal / Cóctel de Playa',
          description: 'Hombres: Guayabera de lino clara con pantalón beige. Mujeres: Vestido largo o midi en tonos cálidos.',
          colors: ['#C85A32', '#E6953B', '#FDEEE2', '#FFFFFF'],
        },
        giftRegistry: {
          enabled: true,
          title: 'Mesa de Regalos',
          description: 'Tu compañía en este paraíso es nuestro mejor regalo.',
          items: [],
        },
        rsvp: {
          enabled: true,
          title: 'Confirmación RSVP',
          deadline: '2026-09-30',
          maxCompanionsPerGuest: 2,
          allowDietaryRestrictions: true,
          customMessage: 'Por favor confirma antes del 30 de Septiembre.',
        },
        qrPass: {
          enabled: true,
          title: 'Pase Playa QR',
          instructions: 'Muestra tu pase en el acceso al hotel.',
        },
      },
    },
  },
];
